### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by meker12** [dshevtsov/whats-new-on-devdocs-from#13]
We don't currently have an automated way to validate that the output in the `tmp/whatsnew.yml` file matches the issues in the GitHub branch.

So for example, Jeff noticed that the script wasn't picking up "New topic" entries because the label in whats_up.yml is incorrect.   I am guessing that he did a GitHub query to validate the results in the script against the repo content.

We should be able to check that during processing, and raise a warning if the GitHub query for "Major update", "New topic", and "Technical change"  issues and script entries don't match.

**Comment by dshevtsov** [comment]
Basically, a GitHub query is what this script does. It just uses API requests instead of a Web form request. Both will always have the same result, thus such automation will be a mere duplication with no additional value (it will never raise warning, because the result will always be identical).
To make the query more transparent (for debugging and other purposes), it may make sense to show the requested query in the terminal's output.

**Comment by dshevtsov** [comment]
Added GitHub query to terminal output in 0.3.0 version for validation.
